# Generated by Django 5.1.6 on 2025-03-02 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('description', models.TextField()),
                ('promotion', models.DecimalField(decimal_places=5, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('seasonality', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.CharField(blank=True, max_length=50, null=True)),
                ('diameter', models.CharField(max_length=100)),
                ('speed_index', models.CharField(max_length=100)),
                ('load_indices', models.IntegerField()),
                ('load_indices_for_double', models.IntegerField()),
                ('characteristics', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categories')),
            ],
        ),
    ]
