# Generated by Django 5.1.6 on 2025-02-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_name_product_diameter_product_characteristics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
