# Generated by Django 5.1.6 on 2025-03-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_categories_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristics',
        ),
    ]
