# Generated by Django 5.1.6 on 2025-03-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_characteristics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='inStock',
        ),
    ]
