# Generated by Django 5.1.6 on 2025-03-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_average_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inStock',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='set',
            field=models.BooleanField(default=False),
        ),
    ]
