# Generated by Django 5.1.6 on 2025-03-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_instock_product_quantity_product_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='load_indices',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='load_indices_for_double',
            field=models.CharField(max_length=200),
        ),
    ]
