# Generated by Django 5.1.6 on 2025-03-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_load_indices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
    ]
