# Generated by Django 5.1.6 on 2025-03-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_price_alter_product_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotion_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
