# Generated by Django 5.1.6 on 2025-03-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_promotion_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotion_category',
            field=models.ManyToManyField(blank=True, related_name='promotion_products', to='product.category'),
        ),
    ]
