# Generated by Django 5.1.6 on 2025-03-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_promotion_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='set',
        ),
    ]
