# Generated by Django 4.2.9 on 2024-03-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalNoiseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decibel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FuelEconomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GripOnWetSurfaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoadIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoadIndexForDual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dual', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Seasonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpeedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Width',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('state', models.BooleanField(blank=True, default=False, null=True)),
                ('discount', models.BooleanField(blank=True, default=False, null=True)),
                ('runflat', models.BooleanField(blank=True, default=False, null=True)),
                ('offroad', models.BooleanField(blank=True, default=False, null=True)),
                ('set', models.BooleanField(blank=True, null=True)),
                ('in_stock', models.BooleanField(blank=True, null=True)),
                ('car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.cartype')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.category')),
                ('diameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.diameter')),
                ('external_noise_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.externalnoiselevel')),
                ('fuel_economy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.fueleconomy')),
                ('grip_on_wet_surfaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.griponwetsurfaces')),
                ('load_index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.loadindex')),
                ('load_index_for_dual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.loadindexfordual')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tires.manufacturer')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.model')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.profile')),
                ('seasonality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.seasonality')),
                ('speed_index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.speedindex')),
                ('width', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.width')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')])),
                ('tires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tires.tires')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
