# Generated by Django 5.0.1 on 2024-01-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Diameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalNoiseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decibel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FuelEconomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GripOnWetSurfaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoadIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Seasonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpeedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Width',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('state', models.BooleanField(default=False)),
                ('discount', models.BooleanField(default=False)),
                ('runflat', models.BooleanField(default=False)),
                ('offroad', models.BooleanField(default=False)),
                ('set', models.BooleanField()),
                ('in_stock', models.BooleanField()),
                ('car_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.cartype')),
                ('diameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.diameter')),
                ('external_noise_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.externalnoiselevel')),
                ('fuel_economy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.fueleconomy')),
                ('generator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tires.generator')),
                ('grip_on_wet_surfaces', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.griponwetsurfaces')),
                ('load_index', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.loadindex')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.profile')),
                ('seasonality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.seasonality')),
                ('speed_index', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.speedindex')),
                ('width', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.width')),
            ],
        ),
    ]
