# Generated by Django 5.0.1 on 2024-01-16 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tires',
            name='load_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tires.loadindex'),
        ),
        migrations.AlterField(
            model_name='tires',
            name='price',
            field=models.IntegerField(),
        ),
    ]
