# Generated by Django 4.2.9 on 2024-03-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0003_alter_profile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='diameter',
            old_name='diameter',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='externalnoiselevel',
            old_name='decibel',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='fueleconomy',
            old_name='category',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='griponwetsurfaces',
            old_name='category',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='loadindex',
            old_name='load',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='loadindexfordual',
            old_name='dual',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='width',
            old_name='width',
            new_name='title',
        ),
    ]
