# Generated by Django 4.2.9 on 2024-03-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0005_tires_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tires',
            name='promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
