# Generated by Django 4.2.9 on 2024-03-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0006_tires_promotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together=set(),
        ),
    ]
