# Generated by Django 4.2.9 on 2024-03-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0007_alter_reviews_options_alter_reviews_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='tires',
            new_name='model',
        ),
    ]
