# Generated by Django 4.2.9 on 2024-03-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0008_rename_tires_reviews_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='model',
            new_name='tires',
        ),
    ]
